# Generated by Django 3.0.3 on 2020-04-10 03:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark', models.TextField()),
                ('amount', models.IntegerField()),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('fl', models.FileField(default='', max_length=255, upload_to='media/')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=255)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('_sentiment', models.CharField(default=None, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Submit2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=255)),
                ('tpe', models.CharField(choices=[('T', 'Tiki'), ('S', 'Shoppe'), ('F', 'FaceBook')], default='T', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rating', models.FloatField()),
                ('sold', models.IntegerField()),
                ('price', models.IntegerField()),
                ('imageURL', models.URLField(default='')),
                ('productURL', models.URLField()),
                ('typeOF', models.CharField(default='Tiki', max_length=20)),
                ('store', models.CharField(default='Tiki Trading', max_length=20)),
                ('sku', models.CharField(default='', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nckh.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cment', models.TextField(default='')),
                ('stmAS', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('star', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nckh.Phone')),
            ],
        ),
    ]
