# Generated by Django 3.0.3 on 2020-04-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nckh', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit2',
        ),
    ]
