# Generated by Django 3.0.3 on 2020-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nckh', '0004_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='comment',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
