# Generated by Django 3.0.3 on 2020-04-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nckh', '0005_auto_20200419_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='date_pub',
        ),
    ]
