# Generated by Django 3.0.3 on 2020-04-19 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nckh', '0006_remove_learn_date_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learn',
            old_name='comment',
            new_name='lcmt',
        ),
        migrations.AddField(
            model_name='learn',
            name='date_publich',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='learn',
            name='tag',
            field=models.IntegerField(),
        ),
    ]
